import turtle

window = turtle.Screen()
window.bgcolor("#8DF2E8")
window.title("My Name with Python Turtle")
pencil = turtle.Turtle()

pencil.up()
pencil.backward(700)
pencil.down()

pencil.color("#260101")
pencil.fillcolor("#41BFB3")

""" M """
pencil.begin_fill()
pencil.left(70)
pencil.forward(200)
pencil.right(135)
pencil.forward(200)
pencil.left(135)
pencil.forward(200)
pencil.right(135)
pencil.forward(200)
pencil.right(90)
pencil.forward(20)
pencil.right(90)
pencil.forward(160)
pencil.left(135)
pencil.forward(200)
pencil.right(135)
pencil.forward(200)
pencil.left(135)
pencil.forward(160)
pencil.right(90)
pencil.forward(20)
pencil.end_fill()

pencil.up()
pencil.right(160)
pencil.forward(350)
pencil.down()

""" A """
pencil.begin_fill()
pencil.left(90)
pencil.forward(200)
pencil.right(90)
pencil.forward(20)
pencil.right(90)
pencil.forward(200)
pencil.right(90)
pencil.forward(20)
pencil.end_fill()

pencil.up()
pencil.left(180)
pencil.forward(60)
pencil.down()

""" R """
pencil.begin_fill()
pencil.forward(220)
pencil.left(90)
pencil.forward(100)
pencil.left(90)
pencil.forward(180)
pencil.left(90)
pencil.forward(20)
pencil.left(90)
pencil.forward(160)
pencil.right(90)
pencil.forward(60)
pencil.right(90)
pencil.forward(180)
pencil.right(90)
pencil.forward(160)
pencil.right(90)
pencil.forward(200)
pencil.left(90)
pencil.forward(20)
pencil.left(90)
pencil.forward(220)
pencil.left(90)
pencil.forward(200)
pencil.end_fill()

pencil.up()
pencil.left(90)
pencil.forward(250)
pencil.down()

""" T """
pencil.begin_fill()
pencil.forward(200)
pencil.left(90)
pencil.forward(200)
pencil.left(90)
pencil.forward(20)
pencil.left(90)
pencil.forward(180)
pencil.right(90)
pencil.forward(160)
pencil.right(90)
pencil.forward(180)
pencil.left(90)
pencil.forward(20)
pencil.left(90)
pencil.forward(200)
pencil.end_fill()

pencil.up()
pencil.left(90)
pencil.forward(250)
pencil.down()

""" I """
pencil.begin_fill()
pencil.forward(200)
pencil.left(90)
pencil.forward(20)
pencil.left(90)
pencil.forward(180)
pencil.right(90)
pencil.forward(70)
pencil.right(90)
pencil.forward(180)
pencil.left(90)
pencil.forward(20)
pencil.left(90)
pencil.forward(180)
pencil.right(90)
pencil.forward(70)
pencil.right(90)
pencil.forward(180)
pencil.left(90)
pencil.forward(20)
pencil.left(90)
pencil.forward(200)
pencil.left(90)
pencil.forward(200)
pencil.end_fill()

pencil.up()
pencil.left(90)
pencil.forward(250)
pencil.down()

""" N """
pencil.begin_fill()
pencil.forward(200)
pencil.left(90)
pencil.forward(20)
pencil.left(90)
pencil.forward(180)
pencil.right(90)
pencil.forward(180)
pencil.left(90)
pencil.forward(20)
pencil.left(90)
pencil.forward(200)
pencil.end_fill()

turtle.done()
